From Random Sample

In [ ]:
import numpy as np
import tensorflow as tf
# create a random vector of shape (10,2)
x = np.random.sample((10,2))
# make a dataset from a numpy array
dataset = tf.data.Dataset.from_tensor_slices(x)
for input, output in dataset:
   print (input, output)

tf.Tensor(0.4702601401046924, shape=(), dtype=float64) tf.Tensor(0.2632584497349306, shape=(), dtype=float64)
tf.Tensor(0.3877108909682646, shape=(), dtype=float64) tf.Tensor(0.6910601715593528, shape=(), dtype=float64)
tf.Tensor(0.7653077170917992, shape=(), dtype=float64) tf.Tensor(0.9852387785288097, shape=(), dtype=float64)
tf.Tensor(0.48048064406170643, shape=(), dtype=float64) tf.Tensor(0.9979283207972416, shape=(), dtype=float64)
tf.Tensor(0.35116800852843366, shape=(), dtype=float64) tf.Tensor(0.7689963732888321, shape=(), dtype=float64)
tf.Tensor(0.5475957564338849, shape=(), dtype=float64) tf.Tensor(0.43043318074227366, shape=(), dtype=float64)
tf.Tensor(0.07702349937413355, shape=(), dtype=float64) tf.Tensor(0.11534071852196137, shape=(), dtype=float64)
tf.Tensor(0.6820795826634743, shape=(), dtype=float64) tf.Tensor(0.6474344205131646, shape=(), dtype=float64)
tf.Tensor(0.12154823643413137, shape=(), dtype=float64) tf.Tensor(0.09997603542141786, shape=(), dtype=float64)
tf.

Features, Labels

In [ ]:
features, labels = (np.random.sample((10,1,2)), np.random.sample((10,1,1)))
dataset = tf.data.Dataset.from_tensor_slices((features,labels))
for input, output in dataset:
   print (input, output)

tf.Tensor([[0.96294914 0.39094441]], shape=(1, 2), dtype=float64) tf.Tensor([[0.71040366]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.56011873 0.28519956]], shape=(1, 2), dtype=float64) tf.Tensor([[0.31520837]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.75607076 0.25518056]], shape=(1, 2), dtype=float64) tf.Tensor([[0.33853568]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.09202876 0.26606955]], shape=(1, 2), dtype=float64) tf.Tensor([[0.72441417]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.85884142 0.79678322]], shape=(1, 2), dtype=float64) tf.Tensor([[0.07194235]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.14815929 0.10323322]], shape=(1, 2), dtype=float64) tf.Tensor([[0.6790701]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.23230195 0.38253802]], shape=(1, 2), dtype=float64) tf.Tensor([[0.87635701]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.3270663  0.92858895]], shape=(1, 2), dtype=float64) tf.Tensor([[0.42932722]], shape=(1, 1), dtype=float64)
tf.Tensor([[0.41914443 0.92246403

From Generator (v1)

In [ ]:
# from generator
import numpy as np
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_v2_behavior()

sequence = np.array([[[1]],[[2],[3]],[[3],[4],[5]]])
def generator():
    for el in sequence:
        yield el
dataset = tf.data.Dataset.from_generator(generator,output_types=tf.int64, output_shapes=(tf.TensorShape([None, 1])))
dataset = dataset.batch(1)
iter = dataset.make_initializable_iterator()
el = iter.get_next()
with tf.Session() as sess:
    sess.run(iter.initializer)
    print(sess.run(el))
    print(sess.run(el))
    print(sess.run(el))

Instructions for updating:
Use output_signature instead
Instructions for updating:
Use output_signature instead


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
[[[1]]]
[[[2]
  [3]]]
[[[3]
  [4]
  [5]]]


Model and Dataset

In [ ]:
import tensorflow as tf
import numpy as np
train, test = tf.keras.datasets.fashion_mnist.load_data()

images, labels = train
images = images/255.0
labels = labels.astype(np.int32)

In [ ]:
fmnist_train_ds = tf.data.Dataset.from_tensor_slices((images, labels))
fmnist_train_ds = fmnist_train_ds.shuffle(5000).batch(32)

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
              metrics=['accuracy'])

In [ ]:
model.fit(fmnist_train_ds, epochs=2)

Epoch 1/2
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5973 - accuracy: 0.7989
Epoch 2/2
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4607 - accuracy: 0.8418


In [ ]:
#infinite dataset
#model.fit(fmnist_train_ds.repeat(), epochs=2, steps_per_epoch=20)

In [ ]:
loss, accuracy = model.evaluate(fmnist_train_ds)
print("Loss :", loss)
print("Accuracy :", accuracy)

1875/1875 [==============================] - 3s 1ms/step - loss: 0.4488 - accuracy: 0.8451
Loss : 0.44879090785980225
Accuracy : 0.8451499938964844


In [ ]:
#loss, accuracy = model.evaluate(fmnist_train_ds.repeat(), steps=10)
#print("Loss :", loss)
#print("Accuracy :", accuracy)

10/10 [==============================] - 0s 2ms/step - loss: 0.4679 - accuracy: 0.8500
Loss : 0.4679049551486969
Accuracy : 0.8500000238418579


In [ ]:
predict_ds = tf.data.Dataset.from_tensor_slices(images).batch(32)
result = model.predict(predict_ds, steps = 10)
print(result.shape)

(320, 10)
