標準做法：先compile一個model,將optimizer填入。之後即可fit evaluate predict

In [3]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Dense(64, kernel_initializer='uniform', input_shape=(10,)))
model.add(layers.Activation('softmax'))

opt = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer=opt)

In [16]:

# make a dataset from a numpy array
import tensorflow as tf
import numpy as np
sample_number = 10
output_dim = 2
input_dim = 3
features, labels = (np.random.sample((sample_number,1,input_dim)), np.round(np.random.sample(size=(sample_number,1,output_dim))))
dataset = tf.data.Dataset.from_tensor_slices((features,labels))






In [17]:
print("features:", features)
print("labels:", labels)

features: [[[0.17662257 0.91546725 0.21037898]]

 [[0.35359902 0.94910701 0.95316672]]

 [[0.04165999 0.12208539 0.73655883]]

 [[0.55373083 0.55991548 0.53560086]]

 [[0.93761687 0.03218848 0.89886092]]

 [[0.12896961 0.19206683 0.70968595]]

 [[0.49356627 0.89947151 0.04966522]]

 [[0.90176011 0.21696857 0.87181943]]

 [[0.51699985 0.34461049 0.02003944]]

 [[0.47331651 0.03166267 0.49683671]]]
labels: [[[0. 0.]]

 [[0. 1.]]

 [[1. 0.]]

 [[0. 1.]]

 [[0. 0.]]

 [[1. 0.]]

 [[0. 1.]]

 [[1. 1.]]

 [[0. 0.]]

 [[1. 1.]]]


In [24]:
model = keras.Sequential()
model.add(layers.Dense(output_dim, kernel_initializer='uniform', input_shape=(input_dim,)))
model.add(layers.Activation('softmax'))
loss_fn = tf.keras.losses.CategoricalCrossentropy()
# Instantiate an optimizer.
optimizer = tf.keras.optimizers.Adam()


In [25]:
# Iterate over the batches of a dataset.

for x, y in dataset:
    # Open a GradientTape.
    with tf.GradientTape() as tape:
        # Forward pass.
        logits = model(x)
        # Loss value for this batch.
        loss_value = loss_fn(y, logits)
        print ("loss_value:", loss_value)
    # Get gradients of loss wrt the weights.
    gradients = tape.gradient(loss_value, model.trainable_weights)

    # Update the weights of the model.
    optimizer.apply_gradients(zip(gradients, model.trainable_weights))

loss_value: tf.Tensor(0.0, shape=(), dtype=float32)
loss_value: tf.Tensor(0.6711867, shape=(), dtype=float32)
loss_value: tf.Tensor(0.69945985, shape=(), dtype=float32)
loss_value: tf.Tensor(0.67332226, shape=(), dtype=float32)
loss_value: tf.Tensor(0.0, shape=(), dtype=float32)
loss_value: tf.Tensor(0.7028944, shape=(), dtype=float32)
loss_value: tf.Tensor(0.66945523, shape=(), dtype=float32)
loss_value: tf.Tensor(1.3868957, shape=(), dtype=float32)
loss_value: tf.Tensor(0.0, shape=(), dtype=float32)
loss_value: tf.Tensor(1.3864517, shape=(), dtype=float32)
